name: Working with Github Environments

on:
  workflow_dispatch:

jobs:
  development:
    runs-on: ubuntu-latest
    environment: Development
    steps:
      - name: Check out repository
        uses: actions/checkout@main
      - name: Install az ml extension
        run: az extension add -n ml -y
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
      - name: Trigger Azure Machine Learning job in Development
        run: |
          az ml job create --file src/job_dev.yml --resource-group az-ml-resource --workspace-name az-ml-workspace-actions --stream


  production:
    needs: development
    runs-on: ubuntu-latest
    environment: Production
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Trigger Azure Machine Learning job in Production
      run: |
        az ml job create --file src/job_prod.yml --resource-group az-ml-resource --workspace-name az-ml-workspace-actions --stream
